// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR8_svgcbC-AnGtJdIwRudpAREBgTaX-s',
    appId: '1:636006196388:web:c160458060d05af8a8f231',
    messagingSenderId: '636006196388',
    projectId: 'iris-glycomapro',
    authDomain: 'iris-glycomapro.firebaseapp.com',
    storageBucket: 'iris-glycomapro.firebasestorage.app',
    measurementId: 'G-4JJETVQ92D',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWQq8t1_v6dJCGS2io-6otbtY6dv7I58g',
    appId: '1:636006196388:ios:66f3e6b4cfd85362a8f231',
    messagingSenderId: '636006196388',
    projectId: 'iris-glycomapro',
    storageBucket: 'iris-glycomapro.firebasestorage.app',
    iosBundleId: 'com.example.iris.iris',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWQq8t1_v6dJCGS2io-6otbtY6dv7I58g',
    appId: '1:636006196388:ios:66f3e6b4cfd85362a8f231',
    messagingSenderId: '636006196388',
    projectId: 'iris-glycomapro',
    storageBucket: 'iris-glycomapro.firebasestorage.app',
    iosBundleId: 'com.example.iris.iris',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJo_2nCk8BgOVCKHXCvbHD_99DrtaBxNM',
    appId: '1:836459073275:android:51b06b6b61d10ba2742a5e',
    messagingSenderId: '836459073275',
    projectId: 'iris-glaucoma',
    storageBucket: 'iris-glaucoma.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlHpKXaXNYAIIfIZQsaobM6B7SiV5W6W8',
    appId: '1:836459073275:web:c92e067d1203dab3742a5e',
    messagingSenderId: '836459073275',
    projectId: 'iris-glaucoma',
    authDomain: 'iris-glaucoma.firebaseapp.com',
    storageBucket: 'iris-glaucoma.firebasestorage.app',
    measurementId: 'G-DKRTDKK4C2',
  );
}
